
export const BREAKPOINT_MOBILE_SMALL = 320
export const BREAKPOINT_MOBILE_LARGE = 480
export const BREAKPOINT_TABLET = 680
export const BREAKPOINT_DESKTOP_SMALL = 1092
export const BREAKPOINT_DESKTOP_LARGE = 1320

